export const PG_ENABLED = Boolean(process.env.DATABASE_URL);

export let pool = null;

async function getPool() {
  if (!PG_ENABLED) {
    throw new Error('DATABASE_URL is not configured');
  }

  if (!pool) {
    const { Pool } = await import('pg');
    pool = new Pool({
      connectionString: process.env.DATABASE_URL,
      ssl: process.env.DATABASE_URL.includes('sslmode=disable')
        ? false
        : { rejectUnauthorized: false }
    });
  }

  return pool;
}

export async function pgQuery(text, params = []) {
  const pgPool = await getPool();
  return pgPool.query(text, params);
}

export async function pgOne(text, params = []) {
  const result = await pgQuery(text, params);
  return result.rows[0] || null;
}

export async function pgAll(text, params = []) {
  const result = await pgQuery(text, params);
  return result.rows;
}

export async function initPostgresDb() {
  if (!PG_ENABLED) return;

  await pgQuery(`
    CREATE TABLE IF NOT EXISTS users (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name TEXT NOT NULL,
      email TEXT UNIQUE NOT NULL,
      password_hash TEXT NOT NULL,
      last_login_at TIMESTAMPTZ,
      created_source TEXT,
      created_utm_source TEXT,
      login_count INTEGER DEFAULT 0,
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS companies (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name TEXT NOT NULL,
      tax_id TEXT,
      industry TEXT,
      companyAddress TEXT,
      address TEXT,
      plan TEXT NOT NULL DEFAULT 'business',
      owner_id INTEGER NOT NULL,
      billing_status TEXT DEFAULT 'trial',
      subscription_plan TEXT DEFAULT 'engineering_trial',
      subscription_started_at TEXT,
      subscription_expires_at TEXT,
      is_paid_customer INTEGER DEFAULT 0,
      billing_note TEXT,
      has_official_site INTEGER DEFAULT 0,
      official_site_url TEXT,
      official_site_status TEXT DEFAULT 'none',
      official_site_note TEXT,
      is_tester INTEGER DEFAULT 0,
      tester_started_at TEXT,
      tester_note TEXT,
      tester_feedback_status TEXT DEFAULT '尚未回饋',
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS company_users (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      company_id INTEGER NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
      user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      role TEXT NOT NULL DEFAULT 'owner',
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
      UNIQUE(company_id, user_id)
    );

    CREATE TABLE IF NOT EXISTS company_feature_overrides (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      company_id INTEGER NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
      feature_key TEXT NOT NULL,
      enabled INTEGER NOT NULL DEFAULT 1,
      note TEXT,
      updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
      UNIQUE(company_id, feature_key)
    );

    CREATE TABLE IF NOT EXISTS user_login_logs (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_id INTEGER,
      email TEXT,
      ip TEXT,
      user_agent TEXT,
      status TEXT NOT NULL,
      fail_reason TEXT,
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS job_sites (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      company_id INTEGER NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
      name TEXT NOT NULL,
      site_name TEXT,
      client_name TEXT,
      client_phone TEXT,
      address TEXT,
      contact_name TEXT,
      contact_phone TEXT,
      project_type TEXT,
      area_pings REAL DEFAULT 0,
      price_per_ping REAL DEFAULT 0,
      food_cost REAL DEFAULT 0,
      quote_amount REAL DEFAULT 0,
      received_amount REAL DEFAULT 0,
      material_cost REAL DEFAULT 0,
      labor_cost REAL DEFAULT 0,
      outsourced_cost REAL DEFAULT 0,
      misc_cost REAL DEFAULT 0,
      tax_mode TEXT DEFAULT 'not_taxed',
      tax_rate REAL DEFAULT 0.05,
      subtotal_amount REAL DEFAULT 0,
      tax_amount REAL DEFAULT 0,
      total_amount REAL DEFAULT 0,
      estimate_cost_total REAL DEFAULT 0,
      status TEXT NOT NULL DEFAULT '進行中',
      note TEXT,
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS job_site_payments (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      company_id INTEGER NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
      job_site_id INTEGER NOT NULL REFERENCES job_sites(id) ON DELETE CASCADE,
      amount REAL NOT NULL DEFAULT 0,
      payment_date TEXT DEFAULT CURRENT_DATE,
      method TEXT,
      note TEXT,
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS visitor_logs (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      visitor_id TEXT,
      page TEXT,
      referrer TEXT,
      utm_source TEXT,
      utm_medium TEXT,
      utm_campaign TEXT,
      source TEXT,
      ip TEXT,
      user_agent TEXT,
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS traffic_events (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      visitor_id TEXT,
      user_id INTEGER,
      event_type TEXT NOT NULL,
      source TEXT,
      page TEXT,
      referrer TEXT,
      utm_source TEXT,
      utm_medium TEXT,
      utm_campaign TEXT,
      ip TEXT,
      user_agent TEXT,
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS audit_logs (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      company_id INTEGER,
      user_id INTEGER,
      action TEXT NOT NULL,
      detail TEXT,
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS platform_settings (
      key TEXT PRIMARY KEY,
      value TEXT,
      updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    );

    CREATE INDEX IF NOT EXISTS idx_companies_owner_id ON companies(owner_id);
    CREATE INDEX IF NOT EXISTS idx_company_users_user_id ON company_users(user_id);
    CREATE INDEX IF NOT EXISTS idx_job_sites_company_id ON job_sites(company_id);
    CREATE INDEX IF NOT EXISTS idx_job_site_payments_job_site_id ON job_site_payments(job_site_id);
    CREATE INDEX IF NOT EXISTS idx_visitor_logs_source_created ON visitor_logs(source, created_at);
    CREATE INDEX IF NOT EXISTS idx_traffic_events_type_created ON traffic_events(event_type, created_at);
    CREATE INDEX IF NOT EXISTS idx_traffic_events_source_created ON traffic_events(source, created_at);
    CREATE INDEX IF NOT EXISTS idx_user_login_logs_status_created ON user_login_logs(status, created_at);
    CREATE INDEX IF NOT EXISTS idx_user_login_at ON users(last_login_at);
  `);
}
