export const PG_ENABLED = Boolean(process.env.DATABASE_URL);

export let pool = null;

async function getPool() {
  if (!PG_ENABLED) {
    throw new Error('DATABASE_URL is not configured');
  }

  if (!pool) {
    const { Pool } = await import('pg');
    pool = new Pool({
      connectionString: process.env.DATABASE_URL,
      ssl: process.env.DATABASE_URL.includes('sslmode=disable')
        ? false
        : { rejectUnauthorized: false }
    });
  }

  return pool;
}

export async function pgQuery(text, params = []) {
  const pgPool = await getPool();
  return pgPool.query(text, params);
}

export async function pgOne(text, params = []) {
  const result = await pgQuery(text, params);
  return result.rows[0] || null;
}

export async function pgAll(text, params = []) {
  const result = await pgQuery(text, params);
  return result.rows;
}

export async function initPostgresDb() {
  if (!PG_ENABLED) return;

  await pgQuery(`
    CREATE TABLE IF NOT EXISTS users (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name TEXT NOT NULL,
      email TEXT UNIQUE NOT NULL,
      password_hash TEXT NOT NULL,
      last_login_at TIMESTAMPTZ,
      created_source TEXT,
      created_utm_source TEXT,
      login_count INTEGER DEFAULT 0,
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS companies (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name TEXT NOT NULL,
      tax_id TEXT,
      industry TEXT,
      companyAddress TEXT,
      address TEXT,
      plan TEXT NOT NULL DEFAULT 'business',
      owner_id INTEGER NOT NULL,
      billing_status TEXT DEFAULT 'trial',
      subscription_plan TEXT DEFAULT 'engineering_trial',
      subscription_started_at TEXT,
      subscription_expires_at TEXT,
      is_paid_customer INTEGER DEFAULT 0,
      billing_note TEXT,
      has_official_site INTEGER DEFAULT 0,
      official_site_url TEXT,
      official_site_status TEXT DEFAULT 'none',
      official_site_note TEXT,
      is_tester INTEGER DEFAULT 0,
      tester_started_at TEXT,
      tester_note TEXT,
      tester_feedback_status TEXT DEFAULT '尚未回饋',
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS company_users (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      company_id INTEGER NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
      user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      role TEXT NOT NULL DEFAULT 'owner',
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
      UNIQUE(company_id, user_id)
    );

    CREATE TABLE IF NOT EXISTS company_feature_overrides (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      company_id INTEGER NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
      feature_key TEXT NOT NULL,
      enabled INTEGER NOT NULL DEFAULT 1,
      note TEXT,
      updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
      UNIQUE(company_id, feature_key)
    );

    CREATE TABLE IF NOT EXISTS user_login_logs (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_id INTEGER,
      email TEXT,
      ip TEXT,
      user_agent TEXT,
      status TEXT NOT NULL,
      fail_reason TEXT,
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS job_sites (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      company_id INTEGER NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
      name TEXT NOT NULL,
      site_name TEXT,
      client_name TEXT,
      client_phone TEXT,
      address TEXT,
      contact_name TEXT,
      contact_phone TEXT,
      project_type TEXT,
      area_pings REAL DEFAULT 0,
      price_per_ping REAL DEFAULT 0,
      food_cost REAL DEFAULT 0,
      quote_amount REAL DEFAULT 0,
      received_amount REAL DEFAULT 0,
      material_cost REAL DEFAULT 0,
      labor_cost REAL DEFAULT 0,
      outsourced_cost REAL DEFAULT 0,
      misc_cost REAL DEFAULT 0,
      tax_mode TEXT DEFAULT 'not_taxed',
      tax_rate REAL DEFAULT 0.05,
      subtotal_amount REAL DEFAULT 0,
      tax_amount REAL DEFAULT 0,
      total_amount REAL DEFAULT 0,
      estimate_cost_total REAL DEFAULT 0,
      status TEXT NOT NULL DEFAULT '進行中',
      note TEXT,
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS job_site_payments (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      company_id INTEGER NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
      job_site_id INTEGER NOT NULL REFERENCES job_sites(id) ON DELETE CASCADE,
      amount REAL NOT NULL DEFAULT 0,
      payment_date TEXT DEFAULT CURRENT_DATE,
      method TEXT,
      note TEXT,
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS visitor_logs (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      visitor_id TEXT,
      page TEXT,
      referrer TEXT,
      utm_source TEXT,
      utm_medium TEXT,
      utm_campaign TEXT,
      source TEXT,
      ip TEXT,
      user_agent TEXT,
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS traffic_events (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      visitor_id TEXT,
      user_id INTEGER,
      event_type TEXT NOT NULL,
      source TEXT,
      page TEXT,
      referrer TEXT,
      utm_source TEXT,
      utm_medium TEXT,
      utm_campaign TEXT,
      ip TEXT,
      user_agent TEXT,
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS audit_logs (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      company_id INTEGER,
      user_id INTEGER,
      action TEXT NOT NULL,
      detail TEXT,
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS platform_settings (
      key TEXT PRIMARY KEY,
      value TEXT,
      updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS products (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      company_id INTEGER NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
      sku TEXT,
      name TEXT NOT NULL,
      category TEXT,
      unit TEXT,
      price REAL DEFAULT 0,
      cost REAL DEFAULT 0,
      stock REAL DEFAULT 0,
      safety_stock REAL DEFAULT 0,
      supplier TEXT,
      storage_location TEXT,
      note TEXT,
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS suppliers (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      company_id INTEGER NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
      name TEXT NOT NULL,
      phone TEXT,
      email TEXT,
      tax_id TEXT,
      address TEXT,
      contact_person TEXT,
      note TEXT,
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS customers (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      company_id INTEGER NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
      name TEXT NOT NULL,
      phone TEXT,
      email TEXT,
      tax_id TEXT,
      address TEXT,
      contact_person TEXT,
      note TEXT,
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS purchases (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      company_id INTEGER NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
      purchase_no TEXT,
      supplier_id INTEGER,
      supplier_name TEXT,
      purchase_date TEXT DEFAULT CURRENT_DATE,
      category TEXT,
      subtotal REAL DEFAULT 0,
      tax REAL DEFAULT 0,
      total REAL DEFAULT 0,
      paid_amount REAL DEFAULT 0,
      payment_status TEXT DEFAULT '未付款',
      status TEXT DEFAULT 'confirmed',
      note TEXT,
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS purchase_items (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      company_id INTEGER NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
      purchase_id INTEGER NOT NULL REFERENCES purchases(id) ON DELETE CASCADE,
      product_id INTEGER,
      item_name TEXT NOT NULL,
      quantity REAL DEFAULT 0,
      unit TEXT,
      unit_cost REAL DEFAULT 0,
      unit_price REAL DEFAULT 0,
      subtotal REAL DEFAULT 0,
      note TEXT,
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS purchase_payments (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      company_id INTEGER NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
      purchase_id INTEGER NOT NULL REFERENCES purchases(id) ON DELETE CASCADE,
      amount REAL NOT NULL DEFAULT 0,
      payment_date TEXT DEFAULT CURRENT_DATE,
      method TEXT,
      note TEXT,
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS sales (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      company_id INTEGER NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
      customer_id INTEGER,
      customer_name TEXT,
      sale_no TEXT,
      sale_date TEXT DEFAULT CURRENT_DATE,
      category TEXT,
      subtotal REAL DEFAULT 0,
      tax REAL DEFAULT 0,
      total REAL DEFAULT 0,
      collection_status TEXT DEFAULT '未收款',
      received_amount REAL DEFAULT 0,
      status TEXT DEFAULT 'confirmed',
      note TEXT,
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS sale_items (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      company_id INTEGER NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
      sale_id INTEGER NOT NULL REFERENCES sales(id) ON DELETE CASCADE,
      product_id INTEGER,
      item_name TEXT NOT NULL,
      quantity REAL DEFAULT 0,
      unit TEXT,
      unit_price REAL DEFAULT 0,
      subtotal REAL DEFAULT 0,
      note TEXT,
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS sale_receipts (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      company_id INTEGER NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
      sale_id INTEGER NOT NULL REFERENCES sales(id) ON DELETE CASCADE,
      amount REAL NOT NULL DEFAULT 0,
      receipt_date TEXT DEFAULT CURRENT_DATE,
      method TEXT,
      note TEXT,
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS transactions (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      company_id INTEGER NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
      platform_key TEXT,
      channel_type TEXT,
      external_order_id TEXT,
      gross_amount REAL DEFAULT 0,
      platform_fee REAL DEFAULT 0,
      discount_amount REAL DEFAULT 0,
      shipping_fee REAL DEFAULT 0,
      refund_amount REAL DEFAULT 0,
      cost_of_goods_sold REAL DEFAULT 0,
      tax_amount REAL DEFAULT 0,
      net_amount REAL DEFAULT 0,
      profit REAL DEFAULT 0,
      platform_profit REAL DEFAULT 0,
      payment_status TEXT,
      order_status TEXT,
      occurred_at TEXT DEFAULT CURRENT_TIMESTAMP,
      note TEXT,
      items_json TEXT,
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS vouchers (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      company_id INTEGER NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
      type TEXT,
      vendor TEXT,
      amount REAL DEFAULT 0,
      tax REAL DEFAULT 0,
      deductible INTEGER DEFAULT 0,
      voucher_date TEXT DEFAULT CURRENT_DATE,
      note TEXT,
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS platform_accounts (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      company_id INTEGER NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
      platform_key TEXT NOT NULL,
      status TEXT,
      last_sync_at TEXT,
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
      UNIQUE(company_id, platform_key)
    );

    CREATE TABLE IF NOT EXISTS inventory_movements (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      company_id INTEGER NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
      product_id INTEGER,
      job_site_id INTEGER,
      movement_type TEXT,
      quantity REAL DEFAULT 0,
      before_stock REAL DEFAULT 0,
      after_stock REAL DEFAULT 0,
      unit_cost REAL DEFAULT 0,
      note TEXT,
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    );

    ALTER TABLE users ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'pending_review';
    ALTER TABLE users ADD COLUMN IF NOT EXISTS review_status TEXT DEFAULT 'pending_review';
    ALTER TABLE users ADD COLUMN IF NOT EXISTS approval_status TEXT DEFAULT 'pending_review';
    ALTER TABLE users ADD COLUMN IF NOT EXISTS approved_at TEXT;
    ALTER TABLE users ADD COLUMN IF NOT EXISTS approved_by INTEGER;
    ALTER TABLE users ADD COLUMN IF NOT EXISTS rejected_at TEXT;
    ALTER TABLE users ADD COLUMN IF NOT EXISTS rejected_by INTEGER;
    ALTER TABLE users ADD COLUMN IF NOT EXISTS suspended_at TEXT;
    ALTER TABLE users ADD COLUMN IF NOT EXISTS suspended_by INTEGER;
    ALTER TABLE users ADD COLUMN IF NOT EXISTS review_note TEXT;
    ALTER TABLE users ADD COLUMN IF NOT EXISTS terms_accepted_at TEXT;
    ALTER TABLE users ADD COLUMN IF NOT EXISTS terms_version TEXT;
    ALTER TABLE users ADD COLUMN IF NOT EXISTS line_contact TEXT;
    ALTER TABLE users ADD COLUMN IF NOT EXISTS company_stage TEXT;
    ALTER TABLE users ADD COLUMN IF NOT EXISTS phone TEXT;
    ALTER TABLE users ADD COLUMN IF NOT EXISTS contact_name TEXT;
    ALTER TABLE users ADD COLUMN IF NOT EXISTS tax_id TEXT;
    ALTER TABLE users ADD COLUMN IF NOT EXISTS use_case TEXT;

    ALTER TABLE companies ADD COLUMN IF NOT EXISTS review_status TEXT DEFAULT 'pending_review';
    ALTER TABLE companies ADD COLUMN IF NOT EXISTS approval_status TEXT DEFAULT 'pending_review';
    ALTER TABLE companies ADD COLUMN IF NOT EXISTS is_active INTEGER DEFAULT 0;
    ALTER TABLE companies ADD COLUMN IF NOT EXISTS approved_at TEXT;
    ALTER TABLE companies ADD COLUMN IF NOT EXISTS approved_by INTEGER;
    ALTER TABLE companies ADD COLUMN IF NOT EXISTS rejected_at TEXT;
    ALTER TABLE companies ADD COLUMN IF NOT EXISTS rejected_by INTEGER;
    ALTER TABLE companies ADD COLUMN IF NOT EXISTS review_note TEXT;
    ALTER TABLE companies ADD COLUMN IF NOT EXISTS contact_name TEXT;
    ALTER TABLE companies ADD COLUMN IF NOT EXISTS phone TEXT;
    ALTER TABLE companies ADD COLUMN IF NOT EXISTS line_contact TEXT;
    ALTER TABLE companies ADD COLUMN IF NOT EXISTS use_case TEXT;
    ALTER TABLE companies ADD COLUMN IF NOT EXISTS company_stage TEXT;

    CREATE INDEX IF NOT EXISTS idx_companies_owner_id ON companies(owner_id);
    CREATE INDEX IF NOT EXISTS idx_company_users_user_id ON company_users(user_id);
    CREATE INDEX IF NOT EXISTS idx_job_sites_company_id ON job_sites(company_id);
    CREATE INDEX IF NOT EXISTS idx_job_site_payments_job_site_id ON job_site_payments(job_site_id);
    CREATE INDEX IF NOT EXISTS idx_visitor_logs_source_created ON visitor_logs(source, created_at);
    CREATE INDEX IF NOT EXISTS idx_traffic_events_type_created ON traffic_events(event_type, created_at);
    CREATE INDEX IF NOT EXISTS idx_traffic_events_source_created ON traffic_events(source, created_at);
    CREATE INDEX IF NOT EXISTS idx_user_login_logs_status_created ON user_login_logs(status, created_at);
    CREATE INDEX IF NOT EXISTS idx_user_login_at ON users(last_login_at);
    CREATE INDEX IF NOT EXISTS idx_products_company_id ON products(company_id);
    CREATE INDEX IF NOT EXISTS idx_products_created_at ON products(created_at);
    CREATE INDEX IF NOT EXISTS idx_suppliers_company_id ON suppliers(company_id);
    CREATE INDEX IF NOT EXISTS idx_customers_company_id ON customers(company_id);
    CREATE INDEX IF NOT EXISTS idx_purchases_company_id ON purchases(company_id);
    CREATE INDEX IF NOT EXISTS idx_purchases_purchase_date ON purchases(purchase_date);
    CREATE INDEX IF NOT EXISTS idx_sales_company_id ON sales(company_id);
    CREATE INDEX IF NOT EXISTS idx_sales_sale_date ON sales(sale_date);
    CREATE INDEX IF NOT EXISTS idx_transactions_company_id ON transactions(company_id);
    CREATE INDEX IF NOT EXISTS idx_transactions_occurred_at ON transactions(occurred_at);
    CREATE INDEX IF NOT EXISTS idx_transactions_platform_key ON transactions(platform_key);
    CREATE INDEX IF NOT EXISTS idx_vouchers_company_id ON vouchers(company_id);
    CREATE INDEX IF NOT EXISTS idx_platform_accounts_company_id ON platform_accounts(company_id);
    CREATE INDEX IF NOT EXISTS idx_platform_accounts_status ON platform_accounts(status);
    CREATE INDEX IF NOT EXISTS idx_inventory_movements_company_id ON inventory_movements(company_id);
    CREATE INDEX IF NOT EXISTS idx_inventory_movements_created_at ON inventory_movements(created_at);
  `);
}
