import { ENVIRONMENT_STATUS, NODE_ENV } from './env.js';

const requestedProvider = String(process.env.BOOKAI_DB_PROVIDER || '').trim().toLowerCase();
export const PG_ENABLED = !ENVIRONMENT_STATUS.environmentValid || NODE_ENV === 'production' || requestedProvider === 'postgresql' || Boolean(process.env.DATABASE_URL);

export let pool = null;
let poolClosed = false;
let poolClosePromise = null;
let poolCreationPromise = null;

export async function getPool() {
  if (poolClosed) {
    const error = new Error('PostgreSQL pool is closed');
    error.code = 'POSTGRES_POOL_CLOSED';
    throw error;
  }
  if (!PG_ENABLED) {
    throw new Error('DATABASE_URL is not configured');
  }

  if (!process.env.DATABASE_URL) {
    throw new Error('BOOKAI_DB_PROVIDER=postgresql requires DATABASE_URL');
  }

  if (!pool) {
    if (!poolCreationPromise) {
      poolCreationPromise = (async () => {
        const { Pool } = await import('pg');
        if (poolClosed) {
          const error = new Error('PostgreSQL pool is closed');
          error.code = 'POSTGRES_POOL_CLOSED';
          throw error;
        }
        const createdPool = new Pool({
          connectionString: process.env.DATABASE_URL,
          ssl: process.env.DATABASE_URL.includes('sslmode=disable')
            ? false
            : { rejectUnauthorized: false },
          connectionTimeoutMillis: 5000,
          idleTimeoutMillis: 30000,
          max: 10
        });
        createdPool.on('error', (error) => {
          console.error('[postgres] background pool error', {
            code: error?.code || 'POOL_ERROR',
            message: 'PostgreSQL idle connection failed'
          });
        });
        pool = createdPool;
        return createdPool;
      })().finally(() => {
        poolCreationPromise = null;
      });
    }
    return poolCreationPromise;
  }

  return pool;
}

export async function closePostgresPool() {
  if (poolClosePromise) return poolClosePromise;
  poolClosed = true;
  poolClosePromise = (async () => {
    if (poolCreationPromise) {
      try { await poolCreationPromise; } catch {}
    }
    if (!pool) return { closed: false, reason: 'not_created' };
    const activePool = pool;
    pool = null;
    try {
      await activePool.end();
      return { closed: true };
    } catch (error) {
      console.error('[postgres] pool shutdown failed', {
        code: error?.code || 'POOL_CLOSE_FAILED',
        message: 'PostgreSQL pool could not close cleanly'
      });
      return { closed: false, reason: 'close_failed' };
    }
  })();
  return poolClosePromise;
}

export function getPostgresPoolState() {
  return { created: Boolean(pool), closed: poolClosed };
}

export async function pgQuery(text, params = []) {
  const pgPool = await getPool();
  return pgPool.query(text, params);
}

export async function pgOne(text, params = []) {
  const result = await pgQuery(text, params);
  return result.rows[0] || null;
}

export async function pgAll(text, params = []) {
  const result = await pgQuery(text, params);
  return result.rows;
}

// Retained for migration history only. Runtime startup must not execute DDL.
async function legacyInitPostgresDb() {
  if (!PG_ENABLED) return;

  await pgQuery(`
    CREATE TABLE IF NOT EXISTS users (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name TEXT NOT NULL,
      email TEXT UNIQUE NOT NULL,
      password_hash TEXT NOT NULL,
      last_login_at TIMESTAMPTZ,
      created_source TEXT,
      created_utm_source TEXT,
      login_count INTEGER DEFAULT 0,
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS companies (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name TEXT NOT NULL,
      tax_id TEXT,
      industry TEXT,
      companyAddress TEXT,
      address TEXT,
      plan TEXT NOT NULL DEFAULT 'business',
      owner_id INTEGER NOT NULL,
      billing_status TEXT DEFAULT 'trial',
      subscription_plan TEXT DEFAULT 'engineering_trial',
      subscription_started_at TEXT,
      subscription_expires_at TEXT,
      is_paid_customer INTEGER DEFAULT 0,
      billing_note TEXT,
      has_official_site INTEGER DEFAULT 0,
      official_site_url TEXT,
      official_site_status TEXT DEFAULT 'none',
      official_site_note TEXT,
      is_tester INTEGER DEFAULT 0,
      tester_started_at TEXT,
      tester_note TEXT,
      tester_feedback_status TEXT DEFAULT '尚未回饋',
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS company_users (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      company_id INTEGER NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
      user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      role TEXT NOT NULL DEFAULT 'owner',
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
      UNIQUE(company_id, user_id)
    );

    CREATE TABLE IF NOT EXISTS company_feature_overrides (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      company_id INTEGER NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
      feature_key TEXT NOT NULL,
      enabled INTEGER NOT NULL DEFAULT 1,
      note TEXT,
      updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
      UNIQUE(company_id, feature_key)
    );

    CREATE TABLE IF NOT EXISTS user_login_logs (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_id INTEGER,
      email TEXT,
      ip TEXT,
      user_agent TEXT,
      status TEXT NOT NULL,
      fail_reason TEXT,
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS feedbacks (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      company_id INTEGER NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
      user_id INTEGER,
      category TEXT,
      rating INTEGER,
      message TEXT NOT NULL,
      page TEXT,
      status TEXT DEFAULT 'new',
      admin_note TEXT,
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
      updated_at TEXT
    );

    CREATE TABLE IF NOT EXISTS job_sites (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      company_id INTEGER NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
      name TEXT NOT NULL,
      site_name TEXT,
      client_name TEXT,
      client_phone TEXT,
      address TEXT,
      contact_name TEXT,
      contact_phone TEXT,
      project_type TEXT,
      area_pings REAL DEFAULT 0,
      price_per_ping REAL DEFAULT 0,
      food_cost REAL DEFAULT 0,
      quote_amount REAL DEFAULT 0,
      received_amount REAL DEFAULT 0,
      material_cost REAL DEFAULT 0,
      labor_cost REAL DEFAULT 0,
      outsourced_cost REAL DEFAULT 0,
      misc_cost REAL DEFAULT 0,
      tax_mode TEXT DEFAULT 'not_taxed',
      tax_rate REAL DEFAULT 0.05,
      subtotal_amount REAL DEFAULT 0,
      tax_amount REAL DEFAULT 0,
      total_amount REAL DEFAULT 0,
      estimate_cost_total REAL DEFAULT 0,
      status TEXT NOT NULL DEFAULT '進行中',
      note TEXT,
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS job_site_payments (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      company_id INTEGER NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
      job_site_id INTEGER NOT NULL REFERENCES job_sites(id) ON DELETE CASCADE,
      amount REAL NOT NULL DEFAULT 0,
      payment_date TEXT DEFAULT CURRENT_DATE,
      method TEXT,
      note TEXT,
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS job_site_estimate_items (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      company_id INTEGER NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
      job_site_id INTEGER NOT NULL REFERENCES job_sites(id) ON DELETE CASCADE,
      work_type TEXT,
      item_category TEXT,
      item_name TEXT NOT NULL,
      quantity REAL DEFAULT 0,
      unit TEXT,
      unit_price REAL DEFAULT 0,
      amount REAL DEFAULT 0,
      cost_amount REAL DEFAULT 0,
      note TEXT,
      sort_order INTEGER DEFAULT 0,
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS visitor_logs (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      visitor_id TEXT,
      page TEXT,
      referrer TEXT,
      utm_source TEXT,
      utm_medium TEXT,
      utm_campaign TEXT,
      source TEXT,
      ip TEXT,
      user_agent TEXT,
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS traffic_events (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      visitor_id TEXT,
      user_id INTEGER,
      event_type TEXT NOT NULL,
      source TEXT,
      page TEXT,
      referrer TEXT,
      utm_source TEXT,
      utm_medium TEXT,
      utm_campaign TEXT,
      ip TEXT,
      user_agent TEXT,
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS audit_logs (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      company_id INTEGER,
      user_id INTEGER,
      action TEXT NOT NULL,
      detail TEXT,
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS platform_settings (
      key TEXT PRIMARY KEY,
      value TEXT,
      updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS products (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      company_id INTEGER NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
      sku TEXT,
      name TEXT NOT NULL,
      category TEXT,
      unit TEXT,
      price REAL DEFAULT 0,
      cost REAL DEFAULT 0,
      stock REAL DEFAULT 0,
      safety_stock REAL DEFAULT 0,
      supplier TEXT,
      storage_location TEXT,
      note TEXT,
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS suppliers (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      company_id INTEGER NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
      name TEXT NOT NULL,
      phone TEXT,
      email TEXT,
      tax_id TEXT,
      address TEXT,
      contact_person TEXT,
      note TEXT,
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS customers (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      company_id INTEGER NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
      name TEXT NOT NULL,
      phone TEXT,
      email TEXT,
      tax_id TEXT,
      address TEXT,
      contact_person TEXT,
      note TEXT,
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS purchases (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      company_id INTEGER NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
      purchase_no TEXT,
      supplier_id INTEGER,
      supplier_name TEXT,
      purchase_date TEXT DEFAULT CURRENT_DATE,
      category TEXT,
      subtotal REAL DEFAULT 0,
      tax REAL DEFAULT 0,
      total REAL DEFAULT 0,
      paid_amount REAL DEFAULT 0,
      payment_status TEXT DEFAULT '未付款',
      status TEXT DEFAULT 'confirmed',
      note TEXT,
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS purchase_items (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      company_id INTEGER NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
      purchase_id INTEGER NOT NULL REFERENCES purchases(id) ON DELETE CASCADE,
      product_id INTEGER,
      item_name TEXT NOT NULL,
      quantity REAL DEFAULT 0,
      unit TEXT,
      unit_cost REAL DEFAULT 0,
      unit_price REAL DEFAULT 0,
      subtotal REAL DEFAULT 0,
      note TEXT,
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS purchase_payments (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      company_id INTEGER NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
      purchase_id INTEGER NOT NULL REFERENCES purchases(id) ON DELETE CASCADE,
      amount REAL NOT NULL DEFAULT 0,
      payment_date TEXT DEFAULT CURRENT_DATE,
      method TEXT,
      note TEXT,
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS sales (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      company_id INTEGER NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
      customer_id INTEGER,
      customer_name TEXT,
      sale_no TEXT,
      sale_date TEXT DEFAULT CURRENT_DATE,
      category TEXT,
      subtotal REAL DEFAULT 0,
      tax REAL DEFAULT 0,
      total REAL DEFAULT 0,
      collection_status TEXT DEFAULT '未收款',
      received_amount REAL DEFAULT 0,
      status TEXT DEFAULT 'confirmed',
      note TEXT,
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS sale_items (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      company_id INTEGER NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
      sale_id INTEGER NOT NULL REFERENCES sales(id) ON DELETE CASCADE,
      product_id INTEGER,
      item_name TEXT NOT NULL,
      quantity REAL DEFAULT 0,
      unit TEXT,
      unit_price REAL DEFAULT 0,
      subtotal REAL DEFAULT 0,
      unit_cost_snapshot REAL DEFAULT 0,
      cost_subtotal REAL DEFAULT 0,
      note TEXT,
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS sale_receipts (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      company_id INTEGER NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
      sale_id INTEGER NOT NULL REFERENCES sales(id) ON DELETE CASCADE,
      amount REAL NOT NULL DEFAULT 0,
      receipt_date TEXT DEFAULT CURRENT_DATE,
      method TEXT,
      note TEXT,
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS transactions (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      company_id INTEGER NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
      platform_key TEXT,
      channel_type TEXT,
      external_order_id TEXT,
      gross_amount REAL DEFAULT 0,
      platform_fee REAL DEFAULT 0,
      discount_amount REAL DEFAULT 0,
      shipping_fee REAL DEFAULT 0,
      refund_amount REAL DEFAULT 0,
      cost_of_goods_sold REAL DEFAULT 0,
      tax_amount REAL DEFAULT 0,
      net_amount REAL DEFAULT 0,
      profit REAL DEFAULT 0,
      platform_profit REAL DEFAULT 0,
      payment_status TEXT,
      order_status TEXT,
      occurred_at TEXT DEFAULT CURRENT_TIMESTAMP,
      note TEXT,
      items_json TEXT,
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS vouchers (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      company_id INTEGER NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
      type TEXT,
      vendor TEXT,
      amount REAL DEFAULT 0,
      tax REAL DEFAULT 0,
      deductible INTEGER DEFAULT 0,
      voucher_date TEXT DEFAULT CURRENT_DATE,
      note TEXT,
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS invoices (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      company_id INTEGER NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
      invoice_no TEXT NOT NULL,
      invoice_type TEXT NOT NULL DEFAULT 'B2C',
      buyer_name TEXT,
      buyer_tax_id TEXT,
      amount_excl_tax REAL NOT NULL DEFAULT 0,
      tax_amount REAL NOT NULL DEFAULT 0,
      amount_incl_tax REAL NOT NULL DEFAULT 0,
      status TEXT NOT NULL DEFAULT 'draft',
      issued_at TEXT,
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS platform_accounts (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      company_id INTEGER NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
      platform_key TEXT NOT NULL,
      status TEXT,
      last_sync_at TEXT,
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
      UNIQUE(company_id, platform_key)
    );

    CREATE TABLE IF NOT EXISTS inventory_movements (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      company_id INTEGER NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
      product_id INTEGER,
      job_site_id INTEGER,
      movement_type TEXT,
      quantity REAL DEFAULT 0,
      before_stock REAL DEFAULT 0,
      after_stock REAL DEFAULT 0,
      unit_cost REAL DEFAULT 0,
      note TEXT,
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS leads (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      company_id INTEGER NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
      title TEXT NOT NULL,
      client_name TEXT,
      client_phone TEXT,
      source TEXT,
      region TEXT,
      agency_type TEXT,
      project_type TEXT,
      estimated_amount REAL DEFAULT 0,
      estimated_cost REAL DEFAULT 0,
      expected_margin REAL DEFAULT 0,
      risk_level TEXT DEFAULT 'medium',
      fit_score INTEGER DEFAULT 70,
      status TEXT DEFAULT 'new',
      next_action TEXT,
      note TEXT,
      tender_source TEXT,
      tender_ref TEXT,
      converted_job_site_id INTEGER,
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS tenders (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      source TEXT NOT NULL,
      source_tender_id TEXT NOT NULL,
      tender_no TEXT,
      tender_name TEXT NOT NULL,
      agency_name TEXT,
      agency_code TEXT,
      agency_level TEXT,
      region TEXT,
      category TEXT,
      procurement_type TEXT,
      tender_type TEXT,
      announcement_type TEXT,
      budget_amount REAL DEFAULT 0,
      award_amount REAL DEFAULT 0,
      publish_date TEXT,
      deadline_date TEXT,
      opening_date TEXT,
      status TEXT,
      url TEXT,
      raw_payload TEXT,
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
      last_seen_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
      UNIQUE(source, source_tender_id)
    );

    CREATE TABLE IF NOT EXISTS tender_sync_runs (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      source TEXT,
      started_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
      finished_at TIMESTAMPTZ,
      status TEXT DEFAULT 'running',
      fetched_count INTEGER DEFAULT 0,
      inserted_count INTEGER DEFAULT 0,
      updated_count INTEGER DEFAULT 0,
      skipped_count INTEGER DEFAULT 0,
      error_count INTEGER DEFAULT 0,
      error_message TEXT,
      cursor TEXT,
      date_from TEXT,
      date_to TEXT,
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS tender_keywords (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      keyword TEXT NOT NULL UNIQUE,
      category TEXT,
      product_line TEXT,
      enabled INTEGER DEFAULT 1,
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS tender_watch_keywords (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      company_id INTEGER NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
      keyword TEXT NOT NULL,
      region TEXT,
      category TEXT,
      min_budget REAL DEFAULT 0,
      max_budget REAL DEFAULT 0,
      is_active INTEGER DEFAULT 1,
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS tender_radar_sync_states (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      company_id INTEGER NOT NULL UNIQUE REFERENCES companies(id) ON DELETE CASCADE,
      status TEXT DEFAULT 'not_started',
      last_synced_at TIMESTAMPTZ,
      next_suggested_sync_at TIMESTAMPTZ,
      error_message TEXT,
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS tender_matches (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      tender_id INTEGER NOT NULL REFERENCES tenders(id) ON DELETE CASCADE,
      company_id INTEGER,
      keyword TEXT,
      score INTEGER DEFAULT 0,
      matched_reason TEXT,
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS website_settings (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      company_id INTEGER NOT NULL UNIQUE REFERENCES companies(id) ON DELETE CASCADE,
      site_slug TEXT NOT NULL UNIQUE,
      site_name TEXT,
      brand_name TEXT,
      logo_url TEXT,
      favicon_url TEXT,
      primary_color TEXT,
      secondary_color TEXT,
      contact_email TEXT,
      contact_phone TEXT,
      line_url TEXT,
      facebook_url TEXT,
      instagram_url TEXT,
      address TEXT,
      seo_title TEXT,
      seo_description TEXT,
      is_published INTEGER DEFAULT 0,
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS website_banners (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      company_id INTEGER NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
      title TEXT,
      subtitle TEXT,
      image_url TEXT,
      button_text TEXT,
      button_url TEXT,
      sort_order INTEGER DEFAULT 0,
      is_active INTEGER DEFAULT 1,
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS website_home_sections (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      company_id INTEGER NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
      section_type TEXT DEFAULT 'custom',
      title TEXT,
      subtitle TEXT,
      content TEXT,
      image_url TEXT,
      button_text TEXT,
      button_url TEXT,
      sort_order INTEGER DEFAULT 0,
      is_active INTEGER DEFAULT 1,
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS website_products (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      company_id INTEGER NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
      name TEXT NOT NULL,
      slug TEXT NOT NULL,
      description TEXT,
      short_description TEXT,
      price REAL DEFAULT 0,
      compare_at_price REAL DEFAULT 0,
      image_url TEXT,
      category TEXT,
      status TEXT DEFAULT 'draft',
      sort_order INTEGER DEFAULT 0,
      is_featured INTEGER DEFAULT 0,
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
      UNIQUE(company_id, slug)
    );

    CREATE TABLE IF NOT EXISTS website_posts (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      company_id INTEGER NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
      title TEXT NOT NULL,
      slug TEXT NOT NULL,
      summary TEXT,
      content TEXT,
      cover_image_url TEXT,
      category TEXT,
      status TEXT DEFAULT 'draft',
      published_at TEXT,
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
      UNIQUE(company_id, slug)
    );

    CREATE TABLE IF NOT EXISTS website_faqs (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      company_id INTEGER NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
      question TEXT NOT NULL,
      answer TEXT,
      category TEXT,
      sort_order INTEGER DEFAULT 0,
      is_active INTEGER DEFAULT 1,
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS website_inquiries (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      company_id INTEGER NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
      name TEXT,
      email TEXT,
      phone TEXT,
      message TEXT NOT NULL,
      source_page TEXT,
      status TEXT DEFAULT 'new',
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS website_assets (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      company_id INTEGER NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
      file_url TEXT NOT NULL,
      file_name TEXT,
      file_type TEXT,
      file_size INTEGER DEFAULT 0,
      module TEXT,
      created_by INTEGER,
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    );

    ALTER TABLE users ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP;
    ALTER TABLE users ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'pending_review';
    ALTER TABLE users ADD COLUMN IF NOT EXISTS review_status TEXT DEFAULT 'pending_review';
    ALTER TABLE users ADD COLUMN IF NOT EXISTS approval_status TEXT DEFAULT 'pending_review';
    ALTER TABLE users ADD COLUMN IF NOT EXISTS approved_at TEXT;
    ALTER TABLE users ADD COLUMN IF NOT EXISTS approved_by INTEGER;
    ALTER TABLE users ADD COLUMN IF NOT EXISTS rejected_at TEXT;
    ALTER TABLE users ADD COLUMN IF NOT EXISTS rejected_by INTEGER;
    ALTER TABLE users ADD COLUMN IF NOT EXISTS suspended_at TEXT;
    ALTER TABLE users ADD COLUMN IF NOT EXISTS suspended_by INTEGER;
    ALTER TABLE users ADD COLUMN IF NOT EXISTS review_note TEXT;
    ALTER TABLE users ADD COLUMN IF NOT EXISTS terms_accepted_at TEXT;
    ALTER TABLE users ADD COLUMN IF NOT EXISTS terms_version TEXT;
    ALTER TABLE users ADD COLUMN IF NOT EXISTS line_contact TEXT;
    ALTER TABLE users ADD COLUMN IF NOT EXISTS company_stage TEXT;
    ALTER TABLE users ADD COLUMN IF NOT EXISTS phone TEXT;
    ALTER TABLE users ADD COLUMN IF NOT EXISTS contact_name TEXT;
    ALTER TABLE users ADD COLUMN IF NOT EXISTS tax_id TEXT;
    ALTER TABLE users ADD COLUMN IF NOT EXISTS use_case TEXT;
    ALTER TABLE users ADD COLUMN IF NOT EXISTS test_edition TEXT DEFAULT 'commerce';

    ALTER TABLE companies ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP;
    ALTER TABLE companies ADD COLUMN IF NOT EXISTS review_status TEXT DEFAULT 'pending_review';
    ALTER TABLE companies ADD COLUMN IF NOT EXISTS approval_status TEXT DEFAULT 'pending_review';
    ALTER TABLE companies ADD COLUMN IF NOT EXISTS is_active INTEGER DEFAULT 0;
    ALTER TABLE companies ADD COLUMN IF NOT EXISTS approved_at TEXT;
    ALTER TABLE companies ADD COLUMN IF NOT EXISTS approved_by INTEGER;
    ALTER TABLE companies ADD COLUMN IF NOT EXISTS rejected_at TEXT;
    ALTER TABLE companies ADD COLUMN IF NOT EXISTS rejected_by INTEGER;
    ALTER TABLE companies ADD COLUMN IF NOT EXISTS suspended_at TEXT;
    ALTER TABLE companies ADD COLUMN IF NOT EXISTS suspended_by INTEGER;
    ALTER TABLE companies ADD COLUMN IF NOT EXISTS review_note TEXT;
    ALTER TABLE companies ADD COLUMN IF NOT EXISTS contact_name TEXT;
    ALTER TABLE companies ADD COLUMN IF NOT EXISTS phone TEXT;
    ALTER TABLE companies ADD COLUMN IF NOT EXISTS line_contact TEXT;
    ALTER TABLE companies ADD COLUMN IF NOT EXISTS use_case TEXT;
    ALTER TABLE companies ADD COLUMN IF NOT EXISTS company_stage TEXT;
    ALTER TABLE companies ADD COLUMN IF NOT EXISTS beta_status TEXT DEFAULT 'not_started';
    ALTER TABLE companies ADD COLUMN IF NOT EXISTS is_free_beta INTEGER DEFAULT 0;
    ALTER TABLE companies ADD COLUMN IF NOT EXISTS beta_group TEXT;
    ALTER TABLE companies ADD COLUMN IF NOT EXISTS beta_limit_group TEXT;
    ALTER TABLE companies ADD COLUMN IF NOT EXISTS product_line TEXT DEFAULT 'general';
    ALTER TABLE companies ADD COLUMN IF NOT EXISTS industry_type TEXT;
    ALTER TABLE companies ADD COLUMN IF NOT EXISTS beta_approved_at TEXT;
    ALTER TABLE company_users ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP;
    ALTER TABLE sale_items ADD COLUMN IF NOT EXISTS unit_cost_snapshot REAL DEFAULT 0;
    ALTER TABLE sale_items ADD COLUMN IF NOT EXISTS cost_subtotal REAL DEFAULT 0;
    ALTER TABLE website_assets ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP;
    ALTER TABLE tender_watch_keywords ADD COLUMN IF NOT EXISTS region TEXT;
    ALTER TABLE tender_watch_keywords ADD COLUMN IF NOT EXISTS category TEXT;
    ALTER TABLE tender_watch_keywords ADD COLUMN IF NOT EXISTS min_budget REAL DEFAULT 0;
    ALTER TABLE tender_watch_keywords ADD COLUMN IF NOT EXISTS max_budget REAL DEFAULT 0;
    ALTER TABLE tender_watch_keywords ADD COLUMN IF NOT EXISTS is_active INTEGER DEFAULT 1;
    ALTER TABLE tender_watch_keywords ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP;
    ALTER TABLE tender_radar_sync_states ADD COLUMN IF NOT EXISTS next_suggested_sync_at TIMESTAMPTZ;
    ALTER TABLE tender_radar_sync_states ADD COLUMN IF NOT EXISTS error_message TEXT;
    ALTER TABLE tender_radar_sync_states ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP;

    CREATE INDEX IF NOT EXISTS idx_companies_owner_id ON companies(owner_id);
    CREATE INDEX IF NOT EXISTS idx_company_users_user_id ON company_users(user_id);
    CREATE INDEX IF NOT EXISTS idx_job_sites_company_id ON job_sites(company_id);
    CREATE INDEX IF NOT EXISTS idx_job_site_payments_job_site_id ON job_site_payments(job_site_id);
    CREATE INDEX IF NOT EXISTS idx_job_site_estimate_items_company_id ON job_site_estimate_items(company_id);
    CREATE INDEX IF NOT EXISTS idx_job_site_estimate_items_job_site_id ON job_site_estimate_items(job_site_id);
    CREATE INDEX IF NOT EXISTS idx_visitor_logs_source_created ON visitor_logs(source, created_at);
    CREATE INDEX IF NOT EXISTS idx_traffic_events_type_created ON traffic_events(event_type, created_at);
    CREATE INDEX IF NOT EXISTS idx_traffic_events_source_created ON traffic_events(source, created_at);
    CREATE INDEX IF NOT EXISTS idx_user_login_logs_status_created ON user_login_logs(status, created_at);
    CREATE INDEX IF NOT EXISTS idx_feedbacks_company_id ON feedbacks(company_id);
    CREATE INDEX IF NOT EXISTS idx_feedbacks_status ON feedbacks(status);
    CREATE INDEX IF NOT EXISTS idx_user_login_at ON users(last_login_at);
    CREATE INDEX IF NOT EXISTS idx_products_company_id ON products(company_id);
    CREATE INDEX IF NOT EXISTS idx_products_created_at ON products(created_at);
    CREATE INDEX IF NOT EXISTS idx_suppliers_company_id ON suppliers(company_id);
    CREATE INDEX IF NOT EXISTS idx_customers_company_id ON customers(company_id);
    CREATE INDEX IF NOT EXISTS idx_purchases_company_id ON purchases(company_id);
    CREATE INDEX IF NOT EXISTS idx_purchases_purchase_date ON purchases(purchase_date);
    CREATE INDEX IF NOT EXISTS idx_sales_company_id ON sales(company_id);
    CREATE INDEX IF NOT EXISTS idx_sales_sale_date ON sales(sale_date);
    CREATE INDEX IF NOT EXISTS idx_transactions_company_id ON transactions(company_id);
    CREATE INDEX IF NOT EXISTS idx_transactions_occurred_at ON transactions(occurred_at);
    CREATE INDEX IF NOT EXISTS idx_transactions_platform_key ON transactions(platform_key);
    CREATE INDEX IF NOT EXISTS idx_vouchers_company_id ON vouchers(company_id);
    CREATE INDEX IF NOT EXISTS idx_invoices_company_id ON invoices(company_id);
    CREATE INDEX IF NOT EXISTS idx_invoices_status ON invoices(status);
    CREATE INDEX IF NOT EXISTS idx_platform_accounts_company_id ON platform_accounts(company_id);
    CREATE INDEX IF NOT EXISTS idx_platform_accounts_status ON platform_accounts(status);
    CREATE INDEX IF NOT EXISTS idx_inventory_movements_company_id ON inventory_movements(company_id);
    CREATE INDEX IF NOT EXISTS idx_inventory_movements_created_at ON inventory_movements(created_at);
    CREATE INDEX IF NOT EXISTS leads_company_id_idx ON leads(company_id);
    CREATE INDEX IF NOT EXISTS leads_company_status_idx ON leads(company_id, status);
    CREATE INDEX IF NOT EXISTS leads_company_created_idx ON leads(company_id, created_at);
    CREATE INDEX IF NOT EXISTS idx_tenders_source ON tenders(source);
    CREATE INDEX IF NOT EXISTS idx_tenders_status ON tenders(status);
    CREATE INDEX IF NOT EXISTS idx_tenders_publish_date ON tenders(publish_date);
    CREATE INDEX IF NOT EXISTS idx_tenders_deadline_date ON tenders(deadline_date);
    CREATE INDEX IF NOT EXISTS idx_tenders_region ON tenders(region);
    CREATE INDEX IF NOT EXISTS idx_tenders_agency_level ON tenders(agency_level);
    CREATE INDEX IF NOT EXISTS idx_tender_sync_runs_created ON tender_sync_runs(created_at);
    CREATE INDEX IF NOT EXISTS idx_tender_matches_tender_id ON tender_matches(tender_id);
    CREATE INDEX IF NOT EXISTS idx_tender_matches_company_id ON tender_matches(company_id);
    CREATE INDEX IF NOT EXISTS idx_tender_watch_keywords_company_id ON tender_watch_keywords(company_id);
    CREATE INDEX IF NOT EXISTS idx_tender_radar_sync_states_company_id ON tender_radar_sync_states(company_id);
    CREATE INDEX IF NOT EXISTS idx_website_settings_company_id ON website_settings(company_id);
    CREATE INDEX IF NOT EXISTS idx_website_settings_site_slug ON website_settings(site_slug);
    CREATE INDEX IF NOT EXISTS idx_website_banners_company_id ON website_banners(company_id);
    CREATE INDEX IF NOT EXISTS idx_website_home_sections_company_id ON website_home_sections(company_id);
    CREATE INDEX IF NOT EXISTS idx_website_products_company_id ON website_products(company_id);
    CREATE INDEX IF NOT EXISTS idx_website_products_slug ON website_products(company_id, slug);
    CREATE INDEX IF NOT EXISTS idx_website_posts_company_id ON website_posts(company_id);
    CREATE INDEX IF NOT EXISTS idx_website_posts_slug ON website_posts(company_id, slug);
    CREATE INDEX IF NOT EXISTS idx_website_faqs_company_id ON website_faqs(company_id);
    CREATE INDEX IF NOT EXISTS idx_website_inquiries_company_id ON website_inquiries(company_id);
    CREATE INDEX IF NOT EXISTS idx_website_assets_company_id ON website_assets(company_id);
  `);
}

export const REQUIRED_SCHEMA_VERSION = '001_schema_contract';

export async function verifyPostgresSchema() {
  if (!PG_ENABLED) return { ready: true, version: null };
  const result = await pgQuery(
    'SELECT version FROM bookai_schema_migrations WHERE status = $1 ORDER BY version DESC LIMIT 1',
    ['applied']
  );
  const version = result.rows[0]?.version || null;
  if (version !== REQUIRED_SCHEMA_VERSION) {
    const error = new Error('PostgreSQL schema version is not ready');
    error.code = 'POSTGRES_SCHEMA_VERSION_MISMATCH';
    throw error;
  }
  return { ready: true, version };
}
