export const platforms = [
  { platformKey:'shopee', displayName:'Shopee 蝦皮', category:'marketplace', priority:'P0', connectionType:'api', status:'mock' },
  { platformKey:'momo', displayName:'momo 購物', category:'marketplace', priority:'P0', connectionType:'api', status:'mock' },
  { platformKey:'pchome', displayName:'PChome', category:'marketplace', priority:'P1', connectionType:'csv', status:'planned' },
  { platformKey:'yahoo', displayName:'Yahoo 購物', category:'marketplace', priority:'P1', connectionType:'csv', status:'planned' },
  { platformKey:'ruten', displayName:'露天市集', category:'marketplace', priority:'P1', connectionType:'csv', status:'planned' },
  { platformKey:'pinkoi', displayName:'Pinkoi', category:'marketplace', priority:'P2', connectionType:'api', status:'planned' },
  { platformKey:'coupang_tw', displayName:'Coupang Taiwan', category:'marketplace', priority:'P2', connectionType:'api', status:'planned' },
  { platformKey:'pxgo', displayName:'PXGo 全聯線上購', category:'marketplace', priority:'P2', connectionType:'manual', status:'planned' },
  { platformKey:'shopline', displayName:'SHOPLINE', category:'hosted_commerce', priority:'P0', connectionType:'api', status:'mock' },
  { platformKey:'shopify', displayName:'Shopify', category:'hosted_commerce', priority:'P0', connectionType:'api', status:'mock' },
  { platformKey:'91app', displayName:'91APP', category:'hosted_commerce', priority:'P1', connectionType:'api', status:'planned' },
  { platformKey:'woocommerce', displayName:'WooCommerce', category:'hosted_commerce', priority:'P1', connectionType:'api', status:'planned' },
  { platformKey:'cyberbiz', displayName:'Cyberbiz', category:'hosted_commerce', priority:'P1', connectionType:'api', status:'planned' },
  { platformKey:'waca', displayName:'WACA', category:'hosted_commerce', priority:'P2', connectionType:'api', status:'planned' },
  { platformKey:'easystore', displayName:'EasyStore', category:'hosted_commerce', priority:'P2', connectionType:'api', status:'planned' },
  { platformKey:'line_oa', displayName:'LINE 官方帳號', category:'social_commerce', priority:'P1', connectionType:'webhook', status:'planned' },
  { platformKey:'facebook_shop', displayName:'Facebook Shop', category:'social_commerce', priority:'P2', connectionType:'api', status:'planned' },
  { platformKey:'instagram_shop', displayName:'Instagram Shop', category:'social_commerce', priority:'P2', connectionType:'api', status:'planned' },
  { platformKey:'tiktok_shop', displayName:'TikTok Shop', category:'social_commerce', priority:'P1', connectionType:'api', status:'planned' },
  { platformKey:'line_pay', displayName:'LINE Pay', category:'payment', priority:'P0', connectionType:'api', status:'mock' },
  { platformKey:'jkopay', displayName:'街口支付', category:'payment', priority:'P1', connectionType:'api', status:'planned' },
  { platformKey:'ecpay', displayName:'綠界 ECPay', category:'payment', priority:'P0', connectionType:'api', status:'mock' },
  { platformKey:'newebpay', displayName:'藍新 NewebPay', category:'payment', priority:'P1', connectionType:'api', status:'planned' },
  { platformKey:'stripe', displayName:'Stripe', category:'payment', priority:'P2', connectionType:'api', status:'planned' },
  { platformKey:'ichef', displayName:'iCHEF', category:'pos', priority:'P0', connectionType:'api', status:'mock' },
  { platformKey:'ocard', displayName:'Ocard', category:'pos', priority:'P1', connectionType:'api', status:'planned' },
  { platformKey:'square', displayName:'Square', category:'pos', priority:'P2', connectionType:'api', status:'planned' },
  { platformKey:'uber_eats', displayName:'Uber Eats', category:'food_delivery', priority:'P0', connectionType:'csv', status:'mock' },
  { platformKey:'foodpanda', displayName:'foodpanda', category:'food_delivery', priority:'P0', connectionType:'csv', status:'mock' },
  { platformKey:'foodomo', displayName:'foodomo', category:'food_delivery', priority:'P1', connectionType:'api', status:'planned' },
  { platformKey:'inline', displayName:'inline', category:'food_delivery', priority:'P1', connectionType:'api', status:'planned' }
];
